name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
      # RUSTSEC-2023-0071: rsa 0.9.7 Marvin Attack. No fix available right now.
        run: cargo deny check advisories --ignore "RUSTSEC-2023-0071"
